// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw0pGQbZv46pVYPPGOxrh558v_KWCo7p4',
    appId: '1:463621367135:web:08016762dbc437c4cdc2ea',
    messagingSenderId: '463621367135',
    projectId: 'looking-for-random-c3e04',
    authDomain: 'looking-for-random-c3e04.firebaseapp.com',
    storageBucket: 'looking-for-random-c3e04.appspot.com',
    measurementId: 'G-5MDPPGD1J6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYm_24bDgyqIVDvNLuqFaudccHZsyhoGA',
    appId: '1:463621367135:android:26589199b25579c7cdc2ea',
    messagingSenderId: '463621367135',
    projectId: 'looking-for-random-c3e04',
    storageBucket: 'looking-for-random-c3e04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxVcOs1WQsbQebCZk37q3jF5MHK38p3JU',
    appId: '1:463621367135:ios:10b52c4be83b3085cdc2ea',
    messagingSenderId: '463621367135',
    projectId: 'looking-for-random-c3e04',
    storageBucket: 'looking-for-random-c3e04.appspot.com',
    iosBundleId: 'com.example.lfruApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw0pGQbZv46pVYPPGOxrh558v_KWCo7p4',
    appId: '1:463621367135:web:338959bdfa95c1d8cdc2ea',
    messagingSenderId: '463621367135',
    projectId: 'looking-for-random-c3e04',
    authDomain: 'looking-for-random-c3e04.firebaseapp.com',
    storageBucket: 'looking-for-random-c3e04.appspot.com',
    measurementId: 'G-6PVCLHQTC5',
  );
}
